export const ApiUrl = {
    requestotp: 'request-otp',
    varifyotp:'verify-otp',
    varifyotpmobile:'request-otp',
    signUp:'signup',
    Login:'login',
    Forgot:'request-otp-forgot-password',
    Forgotpassword:'forgot-password',
    addEditAccount:'accounts',
    addEditPayee:'financialBeneficiaries',
    getAllPayees:'financialBeneficiaries',
    getPayeeSummary:'financialBeneficiaries/getSummaryData',
    addEditCategory:'categories',
    getAccount:'accounts',
    accountMonths:'accounts/getMonthlyData',
    payeeMonths:'financialBeneficiaries/getMonthlyData',
    budgetMonths:'financialSources/getMonthlyData',
    categoryMonths:'categories/getMonthlyData',
    classes:'classes',
    getTransactions:'transactions',
    icons:'icons',
    getCategories:'categories',
    getCategorySummaryData:'categories/getSummaryData',
    getBudget:'financialSources',
    getBudgetSummary:'financialSources/getSummaryData',
    addEditBudget:'financialSources',
    addAccountType:'accountTypes',
    getAllAccountType:'accountTypes',
    deleteAccount:'accounts',
    updateAccount:'accounts',
    getAccountSummary:'accounts/getSummaryData',
    addGrop:'groups',
    deleteAccountTypes:'accountTypes',
    getAccountById:'accounts',
    addBill:'bills'

};

