export const ApiUrl = {
    requestotp: 'request-otp',
    varifyotp: 'verify-otp',
    varifyotpmobile: 'request-otp',
    signUp: 'signup',
    Login: 'login',
    Forgot: 'request-otp-forgot-password',
    Forgotpassword: 'forgot-password',
    addEditAccount: 'accounts',
    addEditPayee: 'financialBeneficiaries',
    getAllPayees: 'financialBeneficiaries',
    searchPayeePayer: 'financialBeneficiaries/search',
    getPayeeSummary: 'financialBeneficiaries/getSummaryData',
    addEditCategory: 'categories',
    getAccount: 'accounts',
    searchAccount:'accounts/search',
    accountMonths: 'accounts/getMonthlyData',
    payeeMonths: 'financialBeneficiaries/getMonthlyData',
    budgetMonths: 'financialSources/getMonthlyData',
    categoryMonths: 'categories/getMonthlyData',
    classes: 'classes',
    getTransactions: 'transactions',
    getTransactionsSearch: 'transactions/search',
    icons: 'icons',
    getCategories: 'categories',
    getCategorySummaryData: 'categories/getSummaryData',
    searchCategory: 'categories/search',
    getBudget: 'financialSources',
    getBudgetSummary: 'financialSources/getSummaryData',
    searchBudget: 'financialSources/search',
    addEditBudget: 'financialSources',
    addAccountType: 'accountTypes',
    getAllAccountType: 'accountTypes',
    deleteAccount: 'accounts',
    updateAccount: 'accounts',
    getAccountSummary: 'accounts/getSummaryData',
    addGrop: 'groups',
    deleteAccountTypes: 'accountTypes',
    getAccountById: 'accounts',
    addBill: 'bills',
    addTransfer: 'transferFinancialSources',
    getbill: 'bills',

};

